# Generated by Django 2.2 on 2021-03-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('type_product', models.CharField(choices=[('Desayuno', 'Desayuno'), ('Almuerzo', 'Almuerzo'), ('Cena', 'Cena')], max_length=15)),
            ],
            options={
                'ordering': ['type_product'],
            },
        ),
    ]
